---
version: '3.0'

volumes:
  data:
    driver: local

services:
  squid:
    environment:
      - CLEAN=1
      - LOG_LEVEL=1
    image: docker.io/yaekee/squid:latest
    ports:
      - "3128:3128"
    restart: always
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - data:/var/spool/squid
